version: '3.8'

services:
  app:
    build: .
    container_name: my-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
